export const administrativeAuditMeta = {
  id: "administrative-audit-2025-26",
  title: "Internal Administrative Audit",
  academicYear: "July, 2025 - June, 2026",
  university: "D Y Patil International University Akurdi Pune",
  address: "Sector 29, Pradhikaran, Akurdi, Pune - Maharashtra, INDIA 411044",
  act: "Establishment by Maharashtra Act No. LXIII of 2017",
};

export const administrativeAuditModules = [
  {
    id: "university-information",
    number: "1",
    title: "University Information",
    owner: "Registrar",
    fields: [
      { id: "universityName", label: "Name of the University" },
      { id: "establishmentYear", label: "Year of Establishment" },
      { id: "address", label: "Address", type: "textarea" },
      { id: "pinCode", label: "Pin Code" },
      { id: "website", label: "Website" },
      { id: "viceChancellor", label: "Name of the Vice Chancellor" },
      { id: "vcEmail", label: "Vice Chancellor e-Mail Id", type: "email" },
      { id: "registrar", label: "Name of Registrar" },
      { id: "registrarEmail", label: "Registrar e-Mail Id", type: "email" },
      { id: "accreditation", label: "Accreditation status & Agency", type: "textarea" },
    ],
  },
  {
    id: "courses-offered",
    number: "2",
    title: "Courses Offered",
    owner: "Registrar",
    tables: [
      {
        id: "coursesOffered",
        title: "Courses Offered",
        columns: ["Sr No", "Name of the Program", "Level (UG/PG)", "Intake", "Year of Commencement of the program"],
      },
    ],
  },
  {
    id: "student-statistics",
    number: "3",
    title: "Student Statistics",
    owner: "Registrar",
    tables: [
      {
        id: "studentStatistics",
        title: "Total Number of Students in the university",
        columns: ["Sr No", "Category", "U.G.", "P.G.", "Ph.D.", "Value added / skill Courses"],
        initialRows: [
          { "Sr No": "1", Category: "Open" },
          { "Sr No": "2", Category: "OBC" },
          { "Sr No": "3", Category: "SC" },
          { "Sr No": "4", Category: "ST" },
          { "Sr No": "5", Category: "Others" },
        ],
      },
    ],
  },
  {
    id: "statutory-bodies",
    number: "4",
    title: "Statutory Bodies & ATR",
    owner: "Registrar",
    tables: [
      {
        id: "statutoryBodies",
        title: "Statutory Body Meetings and ATR",
        columns: ["Sr No", "Body / Cell", "Meetings Conducted", "ATR Status", "Remarks / Link"],
        initialRows: [
          { "Sr No": "1", "Body / Cell": "Governing Body" },
          { "Sr No": "2", "Body / Cell": "Board of Management" },
          { "Sr No": "3", "Body / Cell": "Academic Council" },
          { "Sr No": "4", "Body / Cell": "Finance Committee" },
          { "Sr No": "5", "Body / Cell": "ICC" },
          { "Sr No": "6", "Body / Cell": "Student Grievance Cell" },
          { "Sr No": "7", "Body / Cell": "Faculty / Staff Grievance Cell" },
          { "Sr No": "8", "Body / Cell": "Anti Ragging Committee" },
          { "Sr No": "9", "Body / Cell": "Equal opportunity Cell" },
          { "Sr No": "10", "Body / Cell": "IQAC" },
          { "Sr No": "11", "Body / Cell": "Any Other Body / Cell" },
        ],
      },
    ],
  },
  {
    id: "audit-records",
    number: "5",
    title: "Audit Records",
    owner: "Registrar",
    tables: [
      {
        id: "auditRecords",
        title: "Audits Completed",
        columns: ["Sr No", "Audit Type", "Completed Yes / No", "Date", "Remarks / Link"],
        initialRows: [
          { "Sr No": "1", "Audit Type": "Financial Audit" },
          { "Sr No": "2", "Audit Type": "Energy Audit" },
          { "Sr No": "3", "Audit Type": "Environmental Audit" },
          { "Sr No": "4", "Audit Type": "Green Audit" },
          { "Sr No": "5", "Audit Type": "Gender Audit" },
          { "Sr No": "6", "Audit Type": "Academic and Administrative Audit" },
        ],
      },
    ],
  },
  {
    id: "scholarships",
    number: "6",
    title: "Scholarships",
    owner: "Registrar",
    tables: [
      {
        id: "scholarshipSummary",
        title: "Scholarship Details",
        columns: ["Sr No", "Year", "Title of Scholarship", "Number of the Students", "Amount received", "Awarding Agency", "Awarding Organization"],
      },
      {
        id: "scholarshipStudents",
        title: "Scholarship Student Details",
        columns: ["Sr No", "Year", "Title of Scholarship", "Name of the Students", "Amount received", "Awarding Agency"],
      },
    ],
  },
  {
    id: "faculty-staff-details",
    number: "7",
    title: "Faculty & Staff Details",
    owner: "HR",
    fields: [
      { id: "phdQualification", label: "Faculty members with Ph.D qualification" },
      { id: "pgQualification", label: "Post Graduation Qualification" },
      { id: "otherQualification", label: "Any Other Qualification" },
      { id: "studentFacultyRatio", label: "Student Faculty Ratio" },
    ],
    tables: [
      {
        id: "facultyInformation",
        title: "Faculty Information",
        columns: ["Sr No", "Cadre", "Required", "Regular", "Contract"],
        initialRows: [
          { "Sr No": "1", Cadre: "Professors" },
          { "Sr No": "2", Cadre: "Associate Professors" },
          { "Sr No": "3", Cadre: "Assistant Professor" },
          { "Sr No": "4", Cadre: "Total" },
        ],
      },
      {
        id: "facultyTenure",
        title: "Teaching Experience of the Faculty in DYPIU",
        columns: ["Sr No", "Tenure", "No. of Faculty"],
        initialRows: [
          { "Sr No": "1", Tenure: "More than 5 Years" },
          { "Sr No": "2", Tenure: "Between 3 to 5 Years" },
          { "Sr No": "3", Tenure: "Between 1 to 3 Years" },
          { "Sr No": "4", Tenure: "Below 1 Year" },
        ],
      },
      {
        id: "facultyExperience",
        title: "Consolidated Experience of the teaching faculty considering outside experience",
        columns: ["S.No", "Name of the Faculty", "Designation", "Highest Qualification", "Date of Joining", "Experience in DYPIU", "Experience before joining DYPIU (Teaching)", "Total Experience"],
      },
      {
        id: "supportingStaff",
        title: "Details of Admin and Supporting Staff",
        columns: ["S.No", "Name of the Supporting Staff", "Designation", "Highest Qualification", "Date of Joining in DYPIU", "Experience in DYPIU", "Experience before joining DYPIU", "Total Experience"],
      },
      {
        id: "staffTraining",
        title: "Administrative training / professional development program organized for non-teaching staff",
        columns: ["Sr no", "Title of the Course", "Details of resource person", "Duration and date of conduction", "No of beneficiaries"],
      },
    ],
  },
  {
    id: "infrastructure",
    number: "8",
    title: "Infrastructure",
    owner: "Registrar",
    tables: [
      {
        id: "buildingInfrastructure",
        title: "Building Infrastructure",
        columns: ["Sr No", "Facilities", "No."],
        initialRows: [
          { "Sr No": "1", Facilities: "Classrooms" },
          { "Sr No": "2", Facilities: "Laboratories" },
          { "Sr No": "3", Facilities: "Classroom with Smart Panel" },
          { "Sr No": "4", Facilities: "Classroom with Wi-Fi" },
          { "Sr No": "5", Facilities: "Seminar Hall with ICT Facilities" },
          { "Sr No": "6", Facilities: "Computer with ICT Facilities" },
          { "Sr No": "7", Facilities: "Play area facilities" },
          { "Sr No": "8", Facilities: "Common Rooms" },
          { "Sr No": "9", Facilities: "Staff rooms" },
          { "Sr No": "10", Facilities: "Others" },
        ],
      },
      {
        id: "libraryInfrastructure",
        title: "Library & Research Infrastructure",
        columns: ["Sr No", "Facilities", "No."],
        initialRows: [
          { "Sr No": "1", Facilities: "Books (Title and Volumes)" },
          { "Sr No": "2", Facilities: "E-books and Journals" },
          { "Sr No": "3", Facilities: "Journals" },
          { "Sr No": "4", Facilities: "Digital Data base" },
          { "Sr No": "5", Facilities: "CD / Video" },
          { "Sr No": "6", Facilities: "Library Automation" },
          { "Sr No": "7", Facilities: "Others" },
        ],
      },
      {
        id: "eResources",
        title: "E-resource Availability",
        columns: ["Sr No", "Facilities", "Availability", "Remarks"],
        initialRows: [
          { "Sr No": "1", Facilities: "e-journals" },
          { "Sr No": "2", Facilities: "Membership / subscription of e-ShodhSindhu" },
          { "Sr No": "3", Facilities: "Membership / subscription of Shodhganga" },
          { "Sr No": "4", Facilities: "Discipline-specific Databases" },
          { "Sr No": "5", Facilities: "Plagiarism Check software" },
          { "Sr No": "6", Facilities: "Licensed statistical software" },
          { "Sr No": "7", Facilities: "Discipline specific simulation software" },
        ],
      },
      {
        id: "itInfrastructure",
        title: "I.T. (Computer) Infrastructure",
        columns: ["Sr No", "Facilities", "No."],
        initialRows: [
          { "Sr No": "1", Facilities: "No. of Computers in Institute" },
          { "Sr No": "2", Facilities: "No. of Computer exclusively for students only" },
          { "Sr No": "3", Facilities: "No. of Servers" },
          { "Sr No": "4", Facilities: "No. of System Software's" },
          { "Sr No": "5", Facilities: "No. of Application Software's" },
          { "Sr No": "6", Facilities: "Internet Bandwidth" },
          { "Sr No": "7", Facilities: "No. of Wi-Fi Units" },
          { "Sr No": "8", Facilities: "Internet Connectivity" },
        ],
      },
      {
        id: "sportsFacilities",
        title: "Facilities for cultural activities, yoga, games, sports etc",
        columns: ["Sr No", "Facilities", "No."],
      },
      {
        id: "divyangajanFacilities",
        title: "Facilities for Divyangajan",
        columns: ["Sr No", "Facilities", "Available Yes / No"],
        initialRows: [
          { "Sr No": "1", Facilities: "Built environment with ramps / lifts for easy access to classrooms" },
          { "Sr No": "2", Facilities: "Divyangan friendly washrooms" },
          { "Sr No": "3", Facilities: "Signage including tactile path, lights, display boards and signposts" },
          { "Sr No": "4", Facilities: "Assistive technology and facilities for Divyangjan" },
          { "Sr No": "5", Facilities: "Provision for enquiry and information" },
        ],
      },
      {
        id: "researchResources",
        title: "Research Resources",
        columns: ["Sr No", "Facilities", "Availability", "Remarks"],
      },
    ],
  },
  {
    id: "student-activities",
    number: "9",
    title: "Student Activities",
    owner: "Dean Student Welfare",
    tables: [
      {
        id: "hackathons",
        title: "Hackathons and Ideation workshops",
        columns: ["Sr No", "Activity details", "Organized by", "Date of conduction", "Number of beneficiaries / Participants"],
      },
      {
        id: "culturalActivities",
        title: "Cultural Clubs and activities and festivals",
        columns: ["Sr No", "Activity details", "Organized by", "Date of conduction", "Number of beneficiaries / Participants"],
      },
      {
        id: "sportsActivities",
        title: "Sports clubs / teams and activities",
        columns: ["Sr No", "Activity details", "Organized by", "Date of conduction", "Number of beneficiaries / Participants"],
      },
      {
        id: "communityActivities",
        title: "Community related activities",
        columns: ["Sr No", "Activity details", "Organized by", "Date of conduction", "Number of beneficiaries / Participants"],
      },
      {
        id: "studentAwards",
        title: "Awards / Prizes / Recognitions",
        columns: ["Sr No", "Name of the award", "Team / Individual", "Inter-University / State / National / International", "Name of the event", "Name of the student(s)"],
      },
    ],
  },
  {
    id: "placements-internships-training",
    number: "10",
    title: "Placements, Internships & Training",
    owner: "Dean Placement",
    fields: [
      { id: "companiesVisited", label: "Number of companies Visited" },
      { id: "studentsPlaced", label: "Number of Students Placed" },
      { id: "highestSalary", label: "Highest Salary offered" },
      { id: "averageSalary", label: "Average salary offered" },
      { id: "medianSalary", label: "Median Salary offered" },
      { id: "internshipOrganizations", label: "Number of Organizations offered Internships" },
      { id: "studentsInternships", label: "Number of Students carried out Internships" },
      { id: "stipendInternships", label: "Number of Internships carried out with stipend" },
      { id: "totalInternships", label: "Total Number of Internships" },
    ],
    tables: [
      {
        id: "trainingActivities",
        title: "Training Activities / Skill development / Soft skills conducted",
        columns: ["Sr No", "Academic Year", "Title of the Event", "Date of conduction", "No of students benefited"],
      },
    ],
  },
  {
    id: "industry-collaborations",
    number: "11",
    title: "Industry Collaborations",
    owner: "Dean Placement",
    tables: [
      {
        id: "industryCollaborations",
        title: "Industry Collaborations",
        columns: ["Sr No", "Name of the Organization / Institution / Industry with whom MoU is signed", "Year of signing MoU", "Duration of MoU", "List the actual activities under each MoU"],
      },
    ],
  },
  {
    id: "audit-observations",
    number: "12",
    title: "Audit Observations & Recommendations",
    owner: "VC & IQAC",
    fields: [
      { id: "auditObservations", label: "Observations of the Academic Audit Team", type: "textarea" },
      { id: "auditRecommendations", label: "Recommendations of the Audit Team", type: "textarea" },
      { id: "auditorOne", label: "Auditor 1 Name / Designation / Date", type: "textarea" },
      { id: "auditorTwo", label: "Auditor 2 Name / Designation / Date", type: "textarea" },
      { id: "auditorThree", label: "Auditor 3 Name / Designation / Date", type: "textarea" },
      { id: "auditorFour", label: "Auditor 4 Name / Designation / Date", type: "textarea" },
    ],
  },
];
